FROM alpine
ARG version
COPY create-kubeconfig /
ADD https://github.com/containernetworking/plugins/releases/download/v${version}/cni-plugins-linux-arm64-v${version}.tgz /
RUN mkdir /plugins && \
      tar -zxvf /cni-plugins-linux-arm64-v${version}.tgz -C /plugins && \
      rm /cni-plugins-linux-arm64-v${version}.tgz
CMD cp /plugins/* /opt/cni/bin && \
    cp /create-kubeconfig /opt/cni/net.d/create-kubeconfig