name: Docker Image CI

on:
  push:
    tags:
    - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: azure/login-action@v2
      with:
        username: ${{ secrets.DH_USER }}
        password: ${{ secrets.DH_PASSWORD }}
    - name: Set up QEMU dependency
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build controller image
      if: steps.changed-files-plantcontroller.outputs.any_changed == 'true'
      uses: docker/build-push-action@v2
      with:
        context: ${{ env.context }}
        tags: ${{ env.image_name_controller }}
        platforms: linux/arm64,linux/amd64
        push: true
      env:
        context: ./controller
    - name: Build the Docker image
      run: |
        version=$(git describe --abbrev=0 --tags)
        currImage="rockclimber81/cni-plugins:$version"
        latestImage="rockclimber81/cni-plugins"
        docker buildx build --platform linux/amd64,linux/arm64 -t $currImage --build-arg version=${{ vars.version }} -t $latestImage --push .
        docker logout